### ISSUE TITLE
Doesn't work with prettyPrint

### ISSUE THREAD

**Issue by bloodcarter** [pinojs/pino-multi-stream#12]
```
var multistream = require('pino-multi-stream').multistream
var streams = [
  {stream: process.stdout},
  {stream: fs.createWriteStream(_base+'/logs/' + moment().format('YYYY-MM-DD') + '.pino.log')}
]

var pino = require('pino')({
    level: process.env.level || 'info',
    prettyPrint: process.env.stage ? true : false
}, multistream(streams));

 pino.error('test');
```
Gives you:
```
/home/ec2-user/workspace/app.js:26
    logger.error(err);
          ^

TypeError: Cannot read property 'error' of undefined
    at process.<anonymous> (/home/ec2-user/workspace/app.js:26:11)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:292:26)
```

**Comment by mcollina** [comment]
1. you should be using `require('pino-multi-stream')` in place of pino. It does things that you will be responsible to do yourself if you just use multistream.
2. the prettyPrint option cannot be supported with multistream itself as it sits in the same mechanism. Ideally we should throw a better error somewhere

**Comment by bloodcarter** [comment]
Okay, closing then or you will put it in your backlog?

**Comment by mcollina** [comment]
Let's close this.
