### ISSUE TITLE
log.child(obj).info(string) throws 'unknown level' error

### ISSUE THREAD

**Issue by ro70** [pinojs/pino-multi-stream#17]
```
const log = pinoms({streams: streams})
log.child({a: 'A'}).info('TEST')
```
throws
```
/core/node_modules/pino/pino.js:102
     throw Error('unknown level ' + level)
     ^
 
 Error: unknown level undefined
     at EventEmitter._setLevel (/core/node_modules/pino/pino.js:102:11)
     at EventEmitter.value (/core/node_modules/pino-multi-stream/index.js:49:18)
     at applyOptions (/core/node_modules/pino/lib/tools.js:27:8)
     at EventEmitter.child (/core/node_modules/pino/pino.js:201:3)
     at Object.<anonymous> (/core/framework/loggers/index.js:22:5)
     at Module._compile (module.js:624:30)
     at Object.Module._extensions..js (module.js:635:10)
     at Module.load (module.js:545:32)
     at tryModuleLoad (module.js:508:12)
     at Function.Module._load (module.js:500:3)
```

**Comment by mcollina** [comment]
Can you please include a full example?

**Comment by ro70** [comment]
I use a custom stream like
```
{
   level: logLevel,
   stream: {
      write: (str) => {
         // ...
      }
   }
}
```
I set the `logLevel` by a number (instead of a level keyword). This works as long as the number refers to a defined level, e.g. 50 for error. If the number does not refer to a defined level then the error above is thrown.

I'm closing this issue. Thanks for your replies.

**Comment by mcollina** [comment]
I think we should definitely provide a better error message for this, at least.
