### ISSUE TITLE
unknown level undefined error when using prettyPrint

### ISSUE THREAD

**Issue by P4sca1** [pinojs/pino-multi-stream#30]
```
const logger = pinoms({
  base: null,
  level: config.logLevel,
  // prettyPrint: process.env.NODE_ENV !== 'production',
  redact: {
    paths: [
      '*.headers.authorization',
      '*.headers.cookie',
      "*.headers['set-cookie']",
    ],
  },
  streams: [
    // Log everything to stdout
    { stream: process.stdout },
    // In addition to logging to stdout, log error and fatal messages to sentry
    { level: 'error', stream: pinoSentryStream },
    { level: 'fatal', stream: pinoSentryStream },
  ],
})
```
The above code works, however when removing the comment from `prettyPrint` the following error is thrown: 
```
/Users/pascal/code/node_modules/pino-multi-stream/node_modules/pino/lib/levels.js:86
  if (values[level] === undefined) throw Error('unknown level ' + level)
                                         ^
Error: unknown level undefined
    at Pino.setLevel (/Users/pascal/code/node_modules/pino-multi-stream/node_modules/pino/lib/levels.js:86:42)
    at Pino.set level [as level] (/Users/pascal/code/node_modules/pino-multi-stream/node_modules/pino/lib/proto.js:55:45)
    at fixLevel (/Users/pascal/code/node_modules/pino-multi-stream/index.js:33:16)
    at Object.pinoMultiStream [as default] (/Users/pascal/code/node_modules/pino-multi-stream/index.js:27:12)
    at Object.<anonymous> (/Users/pascal/code/projects/daemon/src/utils/logger.ts:15:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile (/Users/pascal/code/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/pascal/code/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

Using `prettyPrint: true` with the default pino package works just fine.

@mcollina Has this anything to do with #29 ?

**Comment by mcollina** [comment]
You’ll need to use https://github.com/pinojs/pino-multi-stream/blob/master/Readme.md#pinomsprettystream-prettyprint--prettifier-dest- to use prettyPrint with multi-stream

**Comment by P4sca1** [comment]
Thank you for the info! :)
The following code is now working:
```ts
import { Transform } from 'stream'

declare module 'pino-multi-stream' {
  function prettyStream(): Transform
}

const logger = pinoms({
  base: null,
  level: config.logLevel,
  redact: {
    paths: [
      '*.headers.authorization',
      '*.headers.cookie',
      "*.headers['set-cookie']",
    ],
  },
  streams: [
    // Log everything to stdout in production, prettify in dev environments.
    {
      stream:
        process.env.NODE_ENV === 'production'
          ? process.stdout
          : pinoms.prettyStream(),
    },
    // In addition to logging to stdout, capture error and fatal messages with sentry
    { level: 'error', stream: pinoSentryStream },
    { level: 'fatal', stream: pinoSentryStream },
  ],
})
```
