### ISSUE TITLE
multi-stream not working with pretty-print

### ISSUE THREAD

**Issue by nlapshin** [pinojs/pino-multi-stream#31]
Today I have tried to pass 'prettyPrint' option when created pino logger instance.

Working example:

```js
  const pinoStreams = pinoms.multistream([
       { stream: pino.destination('/tmp/log1' ) },
       { stream: pino.destination('/tmp/log2') },
  ]);

    const pinoLog = pino({
       level: 'trace
    })(pinoStreams)
```

Not working example:

```js
  const pinoStreams = pinoms.multistream([
       { stream: pino.destination('/tmp/log1' ) },
       { stream: pino.destination('/tmp/log2') },
  ]);

    const pinoLog = pino({
       level: 'trace,
       prettyPrint: { colorize: true } 
    })(pinoStreams)
```

I looked at the source and realized that the context of the call was lost (and with it the this.lastLevel value is not defined).

I used tracing and assume that the call context in the extra wrapper is lost

Working example trace:

```
    at Object.write (/home/nik/workspace/dcloud-server/node_modules/pino-multi-stream/multistream.js:44:13)
    at Pino.write (/home/nik/workspace/dcloud-server/node_modules/pino/lib/proto.js:161:15)
    at Pino.LOG [as info] (/home/nik/workspace/dcloud-server/node_modules/pino/lib/tools.js:38:21)
```

Not working example trace:

```
    _at Object.write (/home/nik/workspace/dcloud-server/node_modules/pino-multi-stream/multistream.js:44:13)
    at Object.write (/home/nik/workspace/dcloud-server/node_modules/pino/lib/tools.js:240:12)
    at Pino.write (/home/nik/workspace/dcloud-server/node_modules/pino/lib/proto.js:161:15)
    at Pino.LOG [as info] (/home/nik/workspace/dcloud-server/node_modules/pino/lib/tools.js:38:21)_
```

**Comment by jsumners** [comment]
Would you like to submit a PR to fix it?

**Comment by nlapshin** [comment]
> Would you like to submit a PR to fix it?

I thought about it, but decided create issue before, because I consider, that need fix it in core pino package. This is where the context is lost.

**Comment by nlapshin** [comment]
> Would you like to submit a PR to fix it?

https://github.com/pinojs/pino/pull/780

I made PR for pino package.
