### ISSUE TITLE
module crashes at the configuration stage

### ISSUE THREAD

**Issue by talentumtuum** [pinojs/pino-multi-stream#69]
Hi, I am trying to use "pino-multi-stream" but I get an error.
```bash
talentumtuum@mac pino-multi-stream-example % node ./src/main.js
/Users/talentumtuum/Documents/me/pino-multi-stream-example/node_modules/pino/lib/levels.js:90
  if (values[level] === undefined) throw Error('unknown level ' + level)
                                   ^

Error: unknown level undefined
    at Pino.setLevel (/Users/talentumtuum/Documents/me/pino-multi-stream-example/node_modules/pino/lib/levels.js:90:42)
    at Pino.set level [as level] (/Users/talentumtuum/Documents/me/pino-multi-stream-example/node_modules/pino/lib/proto.js:63:38)
    at fixLevel (/Users/talentumtuum/Documents/me/pino-multi-stream-example/node_modules/pino-multi-stream/index.js:33:16)
    at pinoMultiStream (/Users/talentumtuum/Documents/me/pino-multi-stream-example/node_modules/pino-multi-stream/index.js:27:12)
    at Object.<anonymous> (/Users/talentumtuum/Documents/me/pino-multi-stream-example/src/main.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```
nodejs version
```bash
talentumtuum@mac pino-multi-stream-example % node -v 
v14.17.0
```

my code
```js
const pinoms = require('pino-multi-stream');
const fs = require('fs');

const logger = pinoms({
    prettyPrint: true,
    streams: [
        { stream: fs.createWriteStream('./all.out') },
        { level: 'info', stream: fs.createWriteStream('./info.out') }
    ]
});

logger.info('hello world');

```

my package.json file
```json
{
  "name": "pino-multi-stream-example",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "pino": "6.13.1",
    "pino-multi-stream": "5.3.0",
    "pino-pretty": "6.0.0"
  }
}

```

**Comment by talentumtuum** [comment]
I created a repository with this problem => https://github.com/talentumtuum/pino-multi-stream-issues-69

**Comment by leorossi** [comment]
Problem appears when using `prettyPrint: true` because the prettifier overwrites the stream symbol in `pino` instance.

So in [this](https://github.com/pinojs/pino-multi-stream/blob/master/index.js#L33) line `minLevel` is undefined. I am working on a PR to fix this

**Comment by leorossi** [comment]
This code actually works, it's slightly different from the example above. I couldn't see what is different in pino's internals though

```
const stream = writeStream(function (data, enc, cb) {
  console.log(data.toString(), 'flushed');
  return cb()
})
const logger = pino({
    prettyPrint: true
  },
    multistream([
      { stream },
      { level: 'info', stream }
    ])
  )
```

This
